@startuml
skinparam linetype ortho
hide circle
skinparam shadowing false

entity DimTiempo {
  +IDTiempo : int <<PK>>
  Año : int
  Cuatrimestre : int
  Mes : int
  NombreMes : varchar
  NombreCuatrimestre : varchar
}

entity DimUbicacionSucursal {
  +IDSucursal : int <<PK>>
  NombreSucursal : varchar
  ProvinciaSucursal : varchar
  LocalidadSucursal : varchar
}

entity DimUbicacionCliente {
  +IDUbicacionCliente : int <<PK>>
  ProvinciaCliente : varchar
  LocalidadCliente : varchar
}

entity DimCliente {
  +IDCliente : int <<PK>>
  Edad : int
  RangoEtario : varchar
  Género : varchar
  IDUbicacionCliente : int <<FK>>
}

entity DimTurnoVenta {
  +IDTurno : int <<PK>>
  HoraInicio : time
  HoraFin : time
  NombreTurno : varchar
}

entity DimTipoMaterial {
  +IDMaterial : int <<PK>>
  TipoMaterial : varchar
}

entity DimModeloSillon {
  +IDModeloSillon : int <<PK>>
  NombreModelo : varchar
  DescripcionModelo : varchar
}

entity DimEstadoPedido {
  +IDEstadoPedido : int <<PK>>
  Estado : varchar
}

entity DimPedido {
  +IDPedido : int <<PK>>
  FechaRegistro : date
  IDSucursal : int <<FK>>
  IDCliente : int <<FK>>
  IDEstadoPedido : int <<FK>>
}

entity DimFabricacion {
  +IDFabricacion : int <<PK>>
  FechaInicio : date
  FechaFin : date
  TiempoFabricacion : int
  IDPedido : int <<FK>>
}

entity DimEnvio {
  +IDEnvio : int <<PK>>
  FechaProgramada : date
  FechaReal : date
  Cumplido : boolean
  CostoEnvioTotal : decimal
  IDUbicacionCliente : int <<FK>>
  IDPedido : int <<FK>>
}

entity FactVentas {
  +IDVenta : int <<PK>>
  IDTiempo : int <<FK>>
  IDSucursal : int <<FK>>
  IDCliente : int <<FK>>
  IDTurno : int <<FK>>
  IDModeloSillon : int <<FK>>
  IDEstadoPedido : int <<FK>>
  ImporteFactura : decimal
  CantidadPedidos : int
}

entity FactCompras {
  +IDCompra : int <<PK>>
  IDTiempo : int <<FK>>
  IDSucursal : int <<FK>>
  IDMaterial : int <<FK>>
  MontoCompra : decimal
}

entity FactEnvios {
  +IDEnvio : int <<PK>>
  IDTiempo : int <<FK>>
  IDUbicacionCliente : int <<FK>>
  IDSucursal : int <<FK>>
  CostoEnvio : decimal
  Cumplido : boolean
}

entity FactFabricacion {
  +IDFabricacion : int <<PK>>
  IDTiempo : int <<FK>>
  IDSucursal : int <<FK>>
  TiempoTotalFabricacion : int
}

' Relaciones
DimCliente }o--|| DimUbicacionCliente
DimPedido }o--|| DimCliente
DimPedido }o--|| DimUbicacionSucursal
DimPedido }o--|| DimEstadoPedido
DimFabricacion }o--|| DimPedido
DimEnvio }o--|| DimUbicacionCliente
DimEnvio }o--|| DimPedido

FactVentas }o--|| DimTiempo
FactVentas }o--|| DimUbicacionSucursal
FactVentas }o--|| DimCliente
FactVentas }o--|| DimTurnoVenta
FactVentas }o--|| DimModeloSillon
FactVentas }o--|| DimEstadoPedido

FactCompras }o--|| DimTiempo
FactCompras }o--|| DimUbicacionSucursal
FactCompras }o--|| DimTipoMaterial

FactEnvios }o--|| DimTiempo
FactEnvios }o--|| DimUbicacionCliente
FactEnvios }o--|| DimUbicacionSucursal

FactFabricacion }o--|| DimTiempo
FactFabricacion }o--|| DimUbicacionSucursal

@enduml
