@startuml
entity BI_Tiempo {
  id BIGINT PRIMARY KEY
  anio INT
  cuatrimestre INT
  mes INT
}

entity BI_ubicacion {
  id BIGINT PRIMARY KEY
  nombre_provincia NVARCHAR(255)
  nombre_localidad NVARCHAR(255)
}

entity BI_rango_etario {
  id BIGINT PRIMARY KEY
  rango NVARCHAR(20)
}

entity BI_turno_venta {
  id BIGINT PRIMARY KEY
  horario_inicio TIME
  horario_fin TIME
}

entity BI_modelo_sillon {
  id BIGINT PRIMARY KEY
  nombre_modelo NVARCHAR(255)
  descripcion NVARCHAR(255)
  precio decimal(18,2)
}

entity BI_estado_pedido {
  id BIGINT PRIMARY KEY
  detalle NVARCHAR(255)
}

entity BI_tipo_material {
  id BIGINT PRIMARY KEY
  descripcion NVARCHAR(255)
}

entity BI_modelo_sillon {
  id BIGINT PRIMARY KEY
  modelo NVARCHAR(255)
  descripcion NVARCHAR(255)
  precio DECIMAL(9)
}
@enduml
