@startuml

entity BI_Tiempo {
  id BIGINT PRIMARY KEY
  anio INT
  cuatrimestre INT
  mes INT
}

entity BI_ubicacion {
  id BIGINT PRIMARY KEY
  nombre_provincia NVARCHAR(255)
  nombre_localidad NVARCHAR(255)
}

entity BI_rango_etario {
  id BIGINT PRIMARY KEY
  rango NVARCHAR(20)
}

entity BI_turno_venta {
  id BIGINT PRIMARY KEY
  horario_inicio TIME
  horario_fin TIME
}

entity BI_ModeloSillon {
  id BIGINT PRIMARY KEY
  nombre_modelo VARCHAR
}

entity BI_EstadoPedido {
  id BIGINT PRIMARY KEY
  detalle NVARCHAR(255)
}

@enduml
